language: cpp
dist: trusty
sudo: required

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libglew-dev

install:
  - ./tools/travis/install_dependencies.sh

script:
  - scons --install-sandbox=`pwd`/dist
