
Import('env')
Import('apiLib')
Import('commonLib')
Import('hostLib')
Import('hostCLib')

pluginsApp = env.Program(
	"mediaio-plugins",
	Glob("plugins/*.c"),
	LIBS = [
		apiLib,
		commonLib,
		hostLib,
		hostCLib,
	]
)

engineApp = env.Program(
	"mediaio",
	Glob("engine/*.c"),
	LIBS = [
		apiLib,
		commonLib,
		hostLib,
		hostCLib,
	]
)

installApp = env.Install("bin", [
	pluginsApp,
	engineApp,
])

env.Alias("install", installApp)
env.Depends(installApp, [
	pluginsApp,
	engineApp
])
