
Import('env')
Import('apiLib')
Import('commonLib')
Import('hostLib')
Import('hostCLib')

pluginsApp = env.Program(
	"mediaio-plugins",
	Glob("plugins/*.c"),
	LIBS = [
		apiLib,
		commonLib,
		hostLib,
		hostCLib,
	]
)

engineApp = env.Program(
	"mediaio",
	Glob("engine/*.c"),
	LIBS = [
		apiLib,
		commonLib,
		hostLib,
		hostCLib,
	]
)

playerApp = env.Program(
	"mediaio-player",
	Glob("player/*.cpp"),
	LIBPATH = [
		"/usr/X11/lib",
	],
	LIBS = [
		apiLib,
		commonLib,
		hostLib,
		hostCLib,
		'GL',
		'GLU',
		'glut',
		'pthread'
	]
)

installApp = env.Install("$PREFIX/usr/bin", [
	pluginsApp,
	engineApp,
	playerApp,
])

env.Alias("install", installApp)
env.Depends(installApp, [
	pluginsApp,
	engineApp,
	playerApp
])
