
Import('env')
Import('conf')
Import('apiLib')
Import('commonLib')
Import('hostLib')
Import('hostCLib')

pluginsApp = env.Program(
	"mediaio-plugins",
	Glob("plugins/*.c"),
	LIBS = [
		apiLib,
		commonLib,
		hostLib,
		hostCLib,
	]
)

env.Alias("install", env.Install("$PREFIX/usr/bin", pluginsApp))

engineApp = env.Program(
	"mediaio",
	Glob("engine/*.c"),
	LIBS = [
		apiLib,
		commonLib,
		hostLib,
		hostCLib,
	]
)

env.Alias("install", env.Install("$PREFIX/usr/bin", engineApp))

opengl_libs = [
	'GL',
	'GLU',
	'glut',
	'pthread'
]

opengl_headers = [
	'GL/gl.h',
	'GL/glut.h',
	'GL/freeglut.h'
]

if(conf.CheckLibWithHeader(opengl_libs, opengl_headers, 'c')):
	playerApp = env.Program(
		"mediaio-player",
		Glob("player/*.cpp"),
		LIBPATH = [
			"/usr/X11/lib",
		],
		LIBS = [
			apiLib,
			commonLib,
			hostLib,
			hostCLib,
			'GL',
			'GLU',
			'glut',
			'pthread'
		]
	)

	env.Alias("install", env.Install("$PREFIX/usr/bin", playerApp))
