
import os
Import('env')

conf = Configure(env)

env = conf.Finish()

commonLib = env.SharedLibrary(
	'mediaio-common',
	Glob('mediaio/common/*.cpp'),
	LIBS = [
	],
)

apiLib = env.SharedLibrary(
	'mediaio-api',
	Glob('mediaio/api/*/*.c'),
	LIBS = [
		commonLib,
	],
)

hostLib = env.SharedLibrary(
	'mediaio-host',
	Glob('mediaio/host/*.cpp'),
	LIBS = [
		apiLib,
		commonLib,
	],
)

hostCLib = env.SharedLibrary(
	'mediaio-host-c',
	Glob('mediaio/host_c/*.cpp'),
	LIBS = [
		commonLib,
		hostLib,
	],
)

env.Alias('install', env.InstallVersionedLib('lib', commonLib))
env.Alias('install', env.InstallVersionedLib('lib', apiLib))
env.Alias('install', env.InstallVersionedLib('lib', hostLib))
env.Alias('install', env.InstallVersionedLib('lib', hostCLib))

paths = [
	'mediaio/api/common',
	'mediaio/api/data',
	'mediaio/api/instance',
	'mediaio/api/metadata',
	'mediaio/api/reader',
	'mediaio/api/writer',
	'mediaio/api/unwrapper',
	'mediaio/api/wrapper',
	'mediaio/api/decoder',
	'mediaio/api/encoder',
	'mediaio/api/generator',
	'mediaio/api/filter',
	'mediaio/api/analyser',
]

for path in paths:
	env.Alias('install', env.Install(os.path.join('include', path), Glob(os.path.join(path, "*.h"))))

Export('commonLib')
Export('apiLib')
Export('hostLib')
Export('hostCLib')
